### ISSUE TITLE
Not pulling 2015 data?

### ISSUE THREAD

**Issue by hsharrison** [bradleyfay/py-Goldsberry#13]
It could very well be that I'm doing something wrong, but I can't seem to get any data from the current season. I'm able to infer that this data is indeed supplied by the API because I can get with [nba_py](https://github.com/seemethere/nba_py), which is a much less convenient package.

**Comment by bradleyfay** [comment]
Can you paste your code so I can check exactly what lines I need to debug?

**Comment by hsharrison** [comment]
Nevermind, after looking through the code it looks like my mistake was not overriding the default `season='2014'` on some functions.

**Comment by bradleyfay** [comment]
Cool. Your finding is useful. I need to update the default for this season and make that aspect more explicit. 

Thanks for sharing and ease share more.

**Comment by hsharrison** [comment]
I was also fooled by the `GameIDs` function which does not include any 2015 games. But looking at the associated issue it appears that requires some manual updating on your part?

**Comment by bradleyfay** [comment]
Yeah. There is a systematic way to create them but there isn't a database to pull them from. 

At least not that I've found. 

My goal is to get everything into a bash script and maybe spin up an Amazon instance that I can point that function to as well as some others that require manual updating. Using a cron job I can make it fairly automated.

**Comment by znmeb** [comment]
@bradleyfay It might be easier to make a Docker image than an Amazon instance. Then any time something changes you just push to GitHub and Docker Hub or Quay.io rebuilds automatically. And you can deploy anywhere there's a Docker host, including on a desktop.

**Comment by bradleyfay** [comment]
Interesting. Sounds very handy. I'll have to read up on that

**Comment by bradleyfay** [comment]
I updated a couple small bugs and made all the default pulls for the 2015 season. 

I haven't added gameids for 2015 yet but these changes should help
