### ISSUE TITLE
Typo in _apiFunc.py

### ISSUE THREAD

**Issue by ppop** [bradleyfay/py-Goldsberry#15]
line 28:
            return '{0}-{1}'.format(y, str(int(y) % 100 + 1)[-2:].zfill(2))
should be:
            return '{0}-{1}'.format(x, str(int(x) % 100 + 1)[-2:].zfill(2))

Thanks for all the hard work!

**Comment by bradleyfay** [comment]
Getting fixed in the refactor!

**Comment by bradleyfay** [comment]
Deprecated helper functions in version 0.7.1. May come back, but for now, new API interaction has eliminated the need for these in the near term
