### ISSUE TITLE
Daily scoreboard/Schedule unavailable

### ISSUE THREAD

**Issue by ppop** [bradleyfay/py-Goldsberry#20]
NBA endpoint changed:

> goldsberry.league.daily_scoreboard(start_date)
> ""Please use the SET_parameters method to set the following paramters 
>    <H1>Referral Denied</H1>  
> You don't have permission to access "http&#58   """

I looked around for another endpoint instead of "scoreboardV2" but no luck.
My best idea would be to parse the "scores" page instead - http://stats.nba.com/scores/#!/02/24/2016 

Any ideas/suggestions?

**Comment by ppop** [comment]
I made a scraper for livescores.com to get just the final results. If anyone is interested I'm happy to share

**Comment by danielmcintosh1** [comment]
Hi Ppop,
Bradley could make a final decision but no reason this functionality couldn't be lumped in with the rest of the package. I think if you create a fork, it can then be merged with the main package.
