### ISSUE TITLE
any way of getting league standing for a given day?

### ISSUE THREAD

**Issue by Peppershaker** [bradleyfay/py-Goldsberry#21]
Is there a known endpoint for this?

Also, whats the format for "StartDate" and "EndDate"

Thanks guys

**Comment by bradleyfay** [comment]
goldsberry.league.playoff_picture() should be close to what you're looking for (I Think). Once you instantiate the class, you can look at the api_params and update the date to try to see what the standings were on a given day in history.

for the date format, stick with `2016-01-15`. I'm almost positive that will work. The webservice actually tries to parse various formats a bit, but that one should get you there.
