### ISSUE TITLE
Getting Usage Rate for NBA Player

### ISSUE THREAD

**Issue by luzer** [bradleyfay/py-Goldsberry#26]
hi

do you have a way to get this?

Usg% Usage Percentage = 
100 * ((FGA + 0.44 * FTA + TOV) * (Tm MP / 5)) / (MP * (Tm FGA + 0.44 * Tm FTA + Tm TOV))

**Comment by luzer** [comment]
i guess i can just calculate it- let me see if i can match other sources

**Comment by danielmcintosh1** [comment]
Hi Luzer,
USG% isn't a value that is directly able to be pulled. However, you should be able to calculate it on your own to within an acceptable margin for error. If you run into any issues, feel free to open a new ticket.

**Comment by luzer** [comment]
i got it close to basketball reference, but not exact... might be because those sites are rounding first and then summing/averaging?

my calc on the bottom

![screen shot 2017-03-18 at 12 52 06 pm](https://cloud.githubusercontent.com/assets/3173585/24074166/bb0fc970-0bd9-11e7-93c9-26bba2ce63da.png)

**Comment by danielmcintosh1** [comment]
The best check we were able to get for similar calcs required calculating MSE for several players. If you find you are high on some and low on the others and the average is pretty spot on, generally it is a rounding issue.
