### ISSUE TITLE
List of Game IDs

### ISSUE THREAD

**Issue by bradleyfay** [bradleyfay/py-Goldsberry#7]
Need to build in a list of game ids so a user can have a list of valid ids.

**Comment by bradleyfay** [comment]
The table should include columns for `home`, `away`, `season type`, `season` in a manner that is searchable by a package user.

**Comment by danielmcintosh1** [comment]
This could also be generalized to other arguments such as playerids, quarter ids, etc. My thinking is that these lists could be passed to other functions to prevent calling quarters that exist in one game say quarter 5, but don't exist in other games with 4 quarters. Would result in an index error and could cause function/ future program to error.

**Comment by bradleyfay** [comment]
Initial table is there. Need to augment with useful information as well as develop a plan for adding data on a daily/weekly basis as games are played.

**Comment by usbogie** [comment]
As a heads up, selecting GameIds from a specific year (like you do in the line i pasted below) returns the GameIds from the current year.

teamids_2006=gameids['HOME_TEAM_ID'].ix[gameids[2006]==filter_season].drop_duplicates().tolist()

**Comment by bradleyfay** [comment]
Have a robust solution to this I think. Need to stress test a bit more. 

Will roll out shortly after refactor and bugs caused by NBA changes are fixed

**Comment by bradleyfay** [comment]
This is solved as of version 0.7.1
